rules:
  - name: "check-console-log"
    extensions: ["js"]
    regex: 'console\.log'
    message: "🚨 'console.log' encontrado no arquivo {file_name} (Linha {line_number})"
    ignore_comments: true
    ignore_paths:
      - "app/js/plugin/multiselect/*"
      - "js/axios/*"
      - "*/Arquivos_HighCharts/*"
      - "*jquery*.js"
      - "*moment.js"

  - name: "check-localhost"
    extensions: ["js"]
    regex: 'http(s)?://(localhost|127\.0\.0\.1)'
    message: "🚨 Uso de 'localhost' detectado na linha {line_number} do arquivo {file_name}"
    ignore_comments: true

  - name: "check-ia-indice"
    extensions: ["py"]
    regex: '^\s*#\s*\d+\.'
    message: "🚨 Comentário de índice encontrado no arquivo {file_name} (Linha {line_number}) - Verifique se é intencional ou foi IA"